Changes in the Swift Lint.
adobe/aepsdk-campaign-ios pull request #40
Opened 2022-01-05 21:10 UTC by shtomar-adb

## Description

Changes in the Swift Lint. Use podspec for installing SwiftLint.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-01-06 17:20 UTC, rymorale commented
these changes look good to me although the latest commit appears to have introduced some lint issues.

2022-01-06 17:21 UTC, rymorale approved these changes

2022-02-04 16:41 UTC, rymorale commented on Makefile
> +	(swiftformat --lint $(PROJECT_NAME)/Sources --swiftversion 5.2)
i believe we want to use 5.1 to be in sync with other AEPSDK extensions.

2022-02-04 16:42 UTC, rymorale approved these changes
looks good to me with just a minor update needed for the swiftformat swift version

2022-02-04 17:57 UTC, swarna04 requested changes

2022-02-04 23:50 UTC, swarna04 approved these changes
👍

2022-02-04 23:55 UTC, merged